apiVersion: v1
kind: ConfigMap
metadata:
  name: airflow-config
  namespace: ml-platform
data:
  AIRFLOW__CORE__EXECUTOR: CeleryExecutor

  AIRFLOW__CELERY__BROKER_URL: redis://redis:6379/0

  AIRFLOW__LOGGING__LOGGING_LEVEL: INFO

  AIRFLOW__CORE__LOAD_EXAMPLES: "False"
